include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true

analyzer:
  exclude:
    - lib/**/*.g.dart

    - lib/generated/**/*.dart
    - lib/temp/**/*.dart
    - test/ignore/**/*.dart

dart:
  exclude:
    - test/temp/**/*.dart
    - test/ignore/**/*.dart
